dist: xenial
language: python
sudo: false
python: 3.7
before_install:
  - sudo apt-get -y install poppler-utils
  - pip install poetry
install:
  - poetry install
notifications:
    email:
        - james@openstates.org
jobs:
  include:
    - script: poetry run flake8 .
      name: "Flake8 Python"
    # - script: poetry run ./text_extract.py test
    #   name: "Test Extraction"
