language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
install: pip install -r requirements-test.txt --use-mirrors
before_script:
    - psql -c "CREATE USER test with PASSWORD 'test' CREATEDB;" -U postgres
script: export PYTHONPATH=.; py.test --cov opencivicdata --ds=opencivicdata.tests.test_settings
after_success:
    - coveralls
notifications:
    email:
        - jturk@sunlightfoundation.com
