language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
install: pip install six pytest pytest-cov mock validictory scrapelib Django dj_database_url coveralls --use-mirrors
script: ./run-tests.sh
after_success:
    - coveralls
notifications:
    email:
        - jturk@sunlightfoundation.com
        - tneale@sunlightfoundation.com
        - paultag@sunlightfoundation.com
