language: python
python:
    - "2.7"
    - "3.3"
install: pip install -r requirements-dev.txt --use-mirrors
script: nosetests
notifications:
    email:
        - jturk@sunlightfoundation.com
        - tneale@sunlightfoundation.com
        - paultag@sunlightfoundation.com
