language: python
dist: xenial
addons:
    postgresql: "10"
    apt:
        packages:
            - "postgresql-10-postgis-2.4"
sudo: false
python:
    - "2.7"
    - "3.5"
    - "3.7"
env:
    - DJANGO_VERSION=1.11
    - DJANGO_VERSION=2.0
    - DJANGO_VERSION=2.1
    - DJANGO_VERSION=2.2
install: 
    - pip install -U setuptools six
    - pip install --pre -e .[dev] Django==$DJANGO_VERSION
before_script:
    - psql -c "CREATE USER test with PASSWORD 'test' CREATEDB SUPERUSER;" -U postgres
    - psql -c "CREATE DATABASE test;" -U postgres
    - psql -c "CREATE EXTENSION postgis;" -U postgres -d test
script:
    - ./run-tests.sh
    - flake8
after_success:
    - coveralls
matrix:
  exclude:
    - python: "2.7"
      env: DJANGO_VERSION=2.0
    - python: "2.7"
      env: DJANGO_VERSION=2.1
    - python: "2.7"
      env: DJANGO_VERSION=2.2
notifications:
    email:
        - james@openstates.org
