language: python
addons:
    postgresql: "9.4"
sudo: false
python:
    - "3.5"
    - "3.6"
env:
    - DJANGO_VERSION=">=1.10,<1.11"
    - DJANGO_VERSION=">=1.11,<2"
install:
    - pip install -r requirements-test.txt
    - pip install Django$DJANGO_VERSION
before_script:
    - psql -c "CREATE USER test with PASSWORD 'test' CREATEDB SUPERUSER;" -U postgres
    - psql -c "CREATE DATABASE test;" -U postgres
    - psql -c "CREATE EXTENSION postgis;" -U postgres -d test
script: 
  - ./run-tests.sh
  - flake8 pupa
after_success:
    - coveralls
notifications:
    email:
        - james@openstates.org
