[tool.poetry]
name = "metadata"
version = "0.1.0"
description = ""
authors = ["James Turk <dev@jamesturk.net>"]

[tool.poetry.dependencies]
python = "^3.7"
pyyaml = "^5.3"
django = "^3.0"
attrs = "^19.3"
us = "^1.0"
pytest = "^5.3"
flake8 = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
