[tool.poetry]
name = "text-extraction"
version = "1.0"
description = ""
authors = ["Your Name <you@example.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
scrapelib = "^1.2"
lxml = "^4.4"
opencivicdata = "^2.4"
dj-database-url = "^0.5.0"
click = "^7.0"
flake8 = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.black]
line-length = 99
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | build
  | dist
)/
'''
