[tool.poetry]
name = "text-extraction"
version = "1.0"
description = ""
authors = ["James Turk <james@openstates.org>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
scrapelib = "^1.2"
lxml = "^4.4"
click = "^7.0"
flake8 = "^3.7"
textract = "^1.6"
chardet = "^3.0"
openstates-core = "^2020.4.1"

[tool.poetry.dev-dependencies]

[tool.black]
line-length = 99
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | build
  | dist
)/
'''
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

