version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    environment:
      CODECOV_TOKEN: "4116c2aa-5968-44f9-98a6-678f98358015"
    docker:
      - image: circleci/python:3.6
      - image: circleci/postgres:11-postgis-ram
        environment:
          POSTGRES_USER: postgres
          POSTGRES_HOST_AUTH_METHOD: trust
    steps:
      - checkout
      - run:
          name: install prereqs
          command: |
            sudo apt-get install -y postgresql-client libgdal-dev libpq-dev libgeos-dev
            pip install poetry

      # python packages
      - restore_cache:
          keys:
            - poetry-cache-v1-{{ checksum "poetry.lock" }}
      - run:
          name: install python packages
          command: poetry install
      - save_cache:
          key: poetry-cache-v1-{{ checksum "poetry.lock" }}
          paths:
            - /home/circleci/.cache/pypoetry/virtualenvs

      # do the work
      - run:
          name: set up database
          command: |
            psql -h localhost -c "CREATE USER test with PASSWORD 'test' CREATEDB SUPERUSER;" -U postgres
            psql -h localhost -c "CREATE DATABASE test;" -U postgres
            psql -h localhost -c "CREATE EXTENSION postgis;" -U postgres -d test
      - run:
          name: test
          command: poetry run pytest --cov-report=xml --cov=openstates_core --junitxml=test_results.xml --ds=openstates_core.test_settings --reuse-db -v openstates_core
          environment:
            DATABASE_URL: postgis://test:test@localhost/test
      - run:
          name: flake8
          command: poetry run flake8 --ignore=E203,E501,W503

      # store results
      - codecov/upload:
          file: coverage.xml
      - store_test_results:
          path: test_results.xml
      - store_artifacts:
          path: test_results.xml
          destination: tr
