version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: install prereqs
          command: |
            pip install poetry

      # python packages
      - restore_cache:
          keys:
            - poetry-cache-v1-{{ checksum "poetry.lock" }}
      - run:
          name: install python packages
          command: poetry install
      - save_cache:
          key: poetry-cache-v1-{{ checksum "poetry.lock" }}
          paths:
            - /home/circleci/.cache/pypoetry/virtualenvs

      # do the work
      - run:
          name: test
          command: poetry run pytest --junitxml=test_results.xml
      - run:
          name: flake8
          command: poetry run flake8

      # store results
      - store_test_results:
          path: test_results.xml
      - store_artifacts:
          path: test_results.xml
          destination: tr
