name: Test Python

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Python & dependency installation
    - uses: actions/checkout@v2
    - name: setup Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: install Poetry
      uses: dschep/install-poetry-action@v1.3
    - name: cache Poetry virtualenv
      uses: actions/cache@v2
      id: cache
      with:
        path: ~/.virtualenvs/
        key: poetry-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          poetry-${{ hashFiles('**/poetry.lock') }}
    - name: set poetry config path
      run: poetry config virtualenvs.path ~/.virtualenvs
    - name: install dependencies
      run: poetry install
      # if: steps.cache.outputs.cache-hit != 'true'
     
    - name: lint with flake8
      run: poetry run flake8 openstates_metadata --show-source --statistics
    - name: lint with black
      run: poetry run black --check openstates_metadata 
    - name: pytest
      run: poetry run pytest
