name: Test Python

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DATABASE: test
          POSTGRES_PASSWORD: test
          POSTGRES_USER: postgres
          POSTGRES_HOST_AUTH_METHOD: trust
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    # Python & dependency installation
    - uses: actions/checkout@v2
    - name: setup Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: install Poetry
      uses: dschep/install-poetry-action@v1.3
    - name: cache Poetry virtualenv
      uses: actions/cache@v2
      id: cache
      with:
        path: ~/.virtualenvs/
        key: poetry-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          poetry-${{ hashFiles('**/poetry.lock') }}
    - name: set poetry config path
      run: poetry config virtualenvs.path ~/.virtualenvs
    - name: install dependencies
      run: poetry install
     
    - name: lint with flake8
      run: poetry run flake8 --show-source --statistics --ignore=E203,E501,EW503
    - name: pytest
      run: poetry run pytest --cov-report=xml --cov=openstates ==ds=openstates.test_settings --reuse-db -v openstates
      env: 
        DATABASE_URL: postgresql://test:test@localhost/test
